### ISSUE TITLE
ToDo for initial release

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/scope-lite#1]
[Release v0.1.0](https://github.com/martinmoene/scope-guard-lite/releases/tag/0.1.0):

- [x] Write Readme
- [x] CMake
- [x] CI: AppVeyor
- [x] CI: Travis
- [x] Code
- [x] Tests
- [x] Examples
- [x] Scripts: update version
- [x] Wandbox
- [x] Godbolt
- [x] [Release v0.1.0-alpha ](https://github.com/martinmoene/scope-lite/releases/tag/v0.1.0-alpha)
- [x] Add test for move-construction
- [x] Conan recipe
